# Generated by Django 6.0.8 on 2026-09-25 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Record identification code', max_length=100, verbose_name='Code')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Creation date')),
                ('created_by', models.CharField(help_text='User who created the record', max_length=256, verbose_name='Created by')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp of the last record modification', verbose_name='Last modified date')),
                ('last_modified_by', models.CharField(help_text='User who last modified the record', max_length=256, verbose_name='Modified by')),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'environment',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Record identification code', max_length=100, verbose_name='Code')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Creation date')),
                ('created_by', models.CharField(help_text='User who created the record', max_length=256, verbose_name='Created by')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp of the last record modification', verbose_name='Last modified date')),
                ('last_modified_by', models.CharField(help_text='User who last modified the record', max_length=256, verbose_name='Modified by')),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Record identification code', max_length=100, verbose_name='Code')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Creation date')),
                ('created_by', models.CharField(help_text='User who created the record', max_length=256, verbose_name='Created by')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp of the last record modification', verbose_name='Last modified date')),
                ('last_modified_by', models.CharField(help_text='User who last modified the record', max_length=256, verbose_name='Modified by')),
                ('description', models.CharField(max_length=256)),
                ('definition', models.TextField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.environment')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Record identification code', max_length=100, verbose_name='Code')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Creation date')),
                ('created_by', models.CharField(help_text='User who created the record', max_length=256, verbose_name='Created by')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp of the last record modification', verbose_name='Last modified date')),
                ('last_modified_by', models.CharField(help_text='User who last modified the record', max_length=256, verbose_name='Modified by')),
                ('cpu', models.CharField(max_length=15)),
                ('memory', models.CharField(max_length=15)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
            ],
            options={
                'db_table': 'instance',
            },
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
