# Generated by Django 6.0.8 on 2026-09-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='created_by',
            field=models.CharField(default='ADMIN', help_text='User who created the record', max_length=256, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='last_modified_by',
            field=models.CharField(blank=True, default='ADMIN', help_text='User who last modified the record', max_length=256, null=True, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_by',
            field=models.CharField(default='ADMIN', help_text='User who created the record', max_length=256, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='image',
            name='last_modified_by',
            field=models.CharField(blank=True, default='ADMIN', help_text='User who last modified the record', max_length=256, null=True, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='created_by',
            field=models.CharField(default='ADMIN', help_text='User who created the record', max_length=256, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='last_modified_by',
            field=models.CharField(blank=True, default='ADMIN', help_text='User who last modified the record', max_length=256, null=True, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.CharField(default='ADMIN', help_text='User who created the record', max_length=256, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_modified_by',
            field=models.CharField(blank=True, default='ADMIN', help_text='User who last modified the record', max_length=256, null=True, verbose_name='Modified by'),
        ),
    ]
