# Generated by Django 6.0.8 on 2026-09-26 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_instance_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project'),
        ),
        migrations.AlterField(
            model_name='image',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.environment'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.image'),
        ),
    ]
