# Generated by Django 6.0.8 on 2026-09-26 02:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_environment_project_alter_image_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='port',
            field=models.CharField(blank=True, default='', max_length=50, validators=[core.models.port_binding]),
        ),
        migrations.AddField(
            model_name='setup',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=255, validators=[core.models.volume_mount]),
        ),
    ]
