# Generated by Django 6.0.8 on 2026-09-29 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_image_isprivate_image_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='last_instance_number',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Creation date')),
                ('created_by', models.CharField(default='ADMIN', help_text='User who created the record', max_length=256, verbose_name='Created by')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp of the last record modification', verbose_name='Last modified date')),
                ('last_modified_by', models.CharField(blank=True, default='ADMIN', help_text='User who last modified the record', max_length=256, null=True, verbose_name='Modified by')),
                ('code', models.CharField(editable=False, max_length=128, unique=True)),
                ('number', models.PositiveBigIntegerField(editable=False)),
                ('container_id', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('port', models.CharField(blank=True, default='', editable=False, max_length=50)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.setup')),
            ],
            options={
                'db_table': 'instance',
                'ordering': ('number',),
                'constraints': [models.UniqueConstraint(fields=('setup', 'number'), name='unique_instance_number_per_setup')],
            },
        ),
    ]
